on:
  push:
    branches:
      - main

name: Deploy 'CheckMyTestBot' to Digital Ocean

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: bluerootlabs/checkmytest
      DO_APP_ID: ${{ secrets.DO_APP_ID }}

    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Install the digital ocean ctl (doctl) on the runner
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DO_ACCESS_TOKEN }}

      - name: Login to doctl
        run: |
          doctl registry login

      - name: Build, tag, and push image to digitalocean
        run: |
          sbt checkMyTestProd/docker:publishLocal
          docker tag $IMAGE_NAME registry.digitalocean.com/bluerootlabs-container-reg/$IMAGE_NAME
          docker push registry.digitalocean.com/bluerootlabs-container-reg/$IMAGE_NAME

      - name: Redeploy digital ocean app
        run: |
          doctl app create-deployment --force-rebuild $DO_APP_ID
